---
- hosts: local
  become: true
  tasks:
    - name: Stop the NGINX service
      service:
        name: nginx
        state: stopped
    - name: Uninstall the NGINX application on localhost
      yum:
        name: nginx
        state: absent
